//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public string ProductImage { get; set; }
    }
}
